services:
  - type: web
    name: anti-poaching-backend
    runtime: docker
    plan: free
    region: oregon
    rootDir: anti-poaching-backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: REGION
        value: zimbabwe
      - key: CORS_ORIGINS
        value: https://anti-poaching-frontend.onrender.com
